### ISSUE TITLE
Reusable temp directory

### ISSUE THREAD

**Issue by matthewbauer** [solidsnack/arx#3]
I've got a branch I'm working on for this. Basically, I want to make ```arx``` executables a little bit faster when run a second time. Instead of generating a new token for each invocation, why not just hardcode a hash based on the archive. That way you don't have to extract the archive new every time.

/cc @solidsnack 

Unrelated to this, but I've been using arx for a project of mine called [nix-bundle](https://github.com/matthewbauer/nix-bundle) that creates executables from nix closures. The portability of arx has been really helpful in doing this! The main issue has been dealing with slow startup times. [AppImageKit](https://github.com/probonopd/appimagekit) tries to improve on this by using [zisofs](https://dev.lovelyhq.com/libburnia/web/wikis/zisofs) or squashfs compression which can be decompressed when they're accessed. Anyway, it requires FUSE/ELF to work so it makes things less portable so I think the TAR route is the best way to go.

**Comment by solidsnack** [comment]
This does mean that subsequent runs could interfere with one another, though.

The `./dat` directory will have stuff from the prior run in it, or could have had some files deleted. I'm not sure how to add this in a way that is safe. Maybe as a something enabled with a flag?

**Comment by solidsnack** [comment]
One of the hidden goals of Arx is that the user should never have to SSH into the target system and delete stuff to get it to work -- bad state from a past run shouldn't carry over. This strong suggests that this functionality should be optional.

**Comment by matthewbauer** [comment]
> One of the hidden goals of Arx is that the user should never have to SSH into the target system and delete stuff to get it to work -- bad state from a past run shouldn't carry over

That's definitely useful. Ideally I think it would make sense to check the integrity of the dat folder before using it, but I'm not sure how to do that in a cross platform way.

**Comment by solidsnack** [comment]
I'm not sure there is a performant way to the integrity check. Hash all the contents? We see where that could go.
