### ISSUE TITLE
Building arx on Linux

### ISSUE THREAD

**Issue by maxim-belkin** [solidsnack/arx#5]
Hello fellow githubbers from the Linuxbrew project!

We're trying to build [arx](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/arx.rb) at Linuxbrew/homebrew-core#2526 and are facing the following error ([log](https://circleci.com/gh/Linuxbrew/homebrew-core/5569?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)):
```
System/Posix/ARX/TMPXTools.hs:14:1: error:
    Failed to load interface for ‘Blaze.ByteString.Builder’
    Perhaps you meant
      Data.ByteString.Builder (from bytestring-0.10.8.1)
    Use -v to see a list of the files searched for.

System/Posix/ARX/TMPXTools.hs:15:1: error:
    Failed to load interface for ‘Data.FileEmbed’
    Use -v to see a list of the files searched for.
make: *** [arx] Error 1
```
Can you help us troubleshoot the problem?

**Comment by solidsnack** [comment]
I was recently able to build Arx and `bytestring-0.10.8.1` is what's installed on my Mac.

**Comment by solidsnack** [comment]
Please try recent master. These libraries definitely seem to be legitimate still.
