### ISSUE TITLE
arx doesnt support tar.xz files

### ISSUE THREAD

**Issue by cleverca22** [solidsnack/arx#6]
```
The file magic of some archives:
  /nix/store/vd0f8ay02rbhv63id9r55vig73j58pbc-tarball/tarball/bundle.tar.xz
could not be interpreted.
```

**Comment by solidsnack** [comment]
Working on this. It's just a matter of adding a string to https://github.com/solidsnack/arx/blob/master/System/Posix/ARX/Tar.hs

Might as well support LZMA while I'm at it.

**Comment by solidsnack** [comment]
For today: https://github.com/solidsnack/arx/tree/xz
